testmail/config/routes.rb
Rails.application.routes.draw do

  # root 'top/main#index'
  root "mail_history/main#index"

  # devise
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get   '/users/sign_up/interim' => "users/registrations#interim"
    post  '/users/sign_up/interim' => "users/registrations#interim_create"
    get   '/users/sign_up/interim/result' => "users/registrations#interim_result"
    get   '/users/sign_up/result' => "users/registrations#result"
    get   '/users/profile/edit' => "users/registrations#profile_edit"
    put   '/users/profile' => "users/registrations#profile_update"
    patch   '/users/profile' => "users/registrations#profile_update"
    post  '/users/station/' => "users/registrations#station_create"
    post  '/users/station/:station_id/unit' => "users/registrations#unit_create"
    get   '/users/password/result' => "users/passwords#result"
    get   '/users/password/update_result' => "users/passwords#update_result"
    # sessions.
    get   '/users/sign_out' => 'users/sessions#destroy'
  end

  # 管理画面
  namespace :management do
    get "smtpinfo" => 'smtpinfo#index'
    put "smtpinfo/edit" => 'smtpinfo#edit'
  end

  # メール送信履歴
  namespace :mail_history do
    get "" => "main#index"
    post "get_filter_data" => "main#get_filter_data"
    resources :reserve, controller: 'main', only: [:destroy] do
    end
  end

  # 社員登録
  namespace :staff_register do
    get "" => "main#index"
    post "import_csv" => "main#import_csv"
    post "get_filter_data" => "main#get_filter_data"
    get "export_csv" => "main#export_csv"
    resources :profile, controller: 'main', only: [:new, :edit, :destroy, :create, :update] do
    end
  end

  # メール雛形作成
  resources :mail_template, controller: 'mail_template/main' do
    post "/get_data" => "mail_template/main#get_data"
  end

  namespace :mail_template do
    post "get_filter_data" => "main#get_filter_data"
  end

  # メール予約
  namespace :mail_reservation do
    get "" => "main#index"
    post "" => "main#create"
    post "get_mail_message" => "main#get_mail_message"
  end

  # 開封レポート
  namespace :open_report do
    get ":id"         => "main#show"
    get "export_csv/:id" => "main#export_csv", as: "export"
    post "get_filter_data/:id" => "main#get_filter_data", as: "get_filter_data"
  end

  # beacon
  namespace :beacon do
    get "/"         => "main#index"
  end

  # health_check
  get '/health_check' => 'application#health_check'

  # error
  get '*anything' => 'errors#routing_error'

end

testmail/app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
  belongs_to :company

  scope :enable, -> {where :del_flag => 0}
  scope :company_filter, -> {where :company_id => User.current_user.profile.company_id}

  def from_name
    ""
  end
end

testmail/app/controllers/beacon/main_controller.rb
class Beacon::MainController < ApplicationController

  # 認証なし
  skip_before_filter :authenticate_user!

  def index

    # Get info
    @staff_id_hash = params[:staff_id_hash]
    @serial_number = params[:serial_number]
    @type          = params[:type]
    @error         = false

    if @staff_id_hash.present? & @serial_number.present?

      satff_id            = Staff.decrypt(@staff_id_hash)
      mail_reservation_id = MailReservation.find_by(serial_number: @serial_number).id
      target_params       = {
                              send_status_id:       SendStatus::SENT,
                              staff_id:             satff_id,
                              mail_reservation_id:  mail_reservation_id
      }

      target_send_memeber = SendMember.where(target_params)

      if target_send_memeber.size.zero?
        ## error if no target data
        Rails.logger.error "Mail was opened. But no target data. staff_id = #{satff_id}, mail_reservation_id = #{mail_reservation_id}"
        @error = true
      end

      target_send_memeber.each do |history|
        history.update( open_flag:      SendMember::STATUS_DETECTED, opened_at:      Time.now) if @type == SendMember::TYPE_OPEN and history.open_flag == SendMember::STATUS_NOTYET
        history.update( click_flag:     SendMember::STATUS_DETECTED, clicked_at:     Time.now) if @type == SendMember::TYPE_CLICK and history.click_flag == SendMember::STATUS_NOTYET
        history.update( file_open_flag: SendMember::STATUS_DETECTED, file_opened_at: Time.now) if @type == SendMember::TYPE_FILE_OPEN and history.file_open_flag == SendMember::STATUS_NOTYET
        begin
          history.save!
        rescue => e
          Rails.logger.error "Mail was opened. But fail updating target data. staff_id = #{satff_id}, mail_reservation_id = #{mail_reservation_id}. Throw exception #{e.message}"
          @error = true
        end
      end

    else
      #error log insert here
      Rails.logger.error "Invalid URL. url = #{request.url}"
      @error = true
    end

    if @type == SendMember::TYPE_CLICK
      # responese 200
      redirect_to "/guide/education_contents.pdf"
    else
      render :json => {:status => 200}, :status => 200
    end
  end

end

testmail/app/controllers/mail_history/main_controller.rb
class MailHistory::MainController < ApplicationController
  before_action :set_js_css_path, only: [:index]

  def index
    @mail_datas = MailReservation.company_filter.order("id DESC").page(params[:page]).per(10)
    @page = params[:page]
    #error msg
    gon.error = Rails.application.config.error
  end

  def destroy
    destroy_data = MailReservation.find params[:id]
    raise ActiveRecord::RecordNotFound if destroy_data.blank?
    # destroy_data.destroy
    destroy_data.del_flag = 1
    destroy_data.save
    SendMember.where(mail_reservation_id: params[:id]).update_all(del_flag: 1)
    redirect_to root_path
  end

  def get_filter_data
    word = params[:search_word]

    data = []
    MailReservation.company_filter.order("id DESC").each do |mail_reservation|

      if mail_reservation.send_mail.present?
        subject = mail_reservation.send_mail.subject.to_s
      elsif mail_reservation.mail_template.present?
        subject = mail_reservation.mail_template.subject.to_s
      else
        subject = ""
      end

      if mail_reservation.job_name.to_s.include?(word) or
         subject.include?(word) or
         mail_reservation.reserved_at.to_s.include?(word) or
         mail_reservation.send_at.to_s.include?(word) or
         mail_reservation.created_at.to_s.include?(word)

         write_data mail_reservation, data
      end

    end
    render :json => {:status => 200, :data => data}, :status => 200
  end

  private
    def write_data mail_reservation, data
      success_member = SendMember.where(mail_reservation_id: mail_reservation.id, send_status_id: 2).count.to_s
      all_member = SendMember.where(mail_reservation_id: mail_reservation.id).count.to_s
      data << {
          :id => mail_reservation.id,
          :company => mail_reservation.company,
          :mail_template_id => mail_reservation.mail_template_id,
          :job_name => mail_reservation.job_name,
          :subject => mail_reservation.mail_template.subject,
          :reserved_at => mail_reservation.reserved_at.strftime("%Y/%m/%d %H:%M"),
          :reserved_date => mail_reservation.reserved_date.to_s,
          :send_time_zone => mail_reservation.send_time_zone.display_name,
          :send_at => mail_reservation.send_at.to_s,
          :member_num => success_member + "/" + all_member,
          :created_at => mail_reservation.created_at.to_s
        }
    end

    def set_js_css_path
      @js_css_root = controller_path
    end
end

testmail/app/controllers/mail_reservation/main_controller.rb
class MailReservation::MainController < ApplicationController
  before_action :set_templates, only: [:index]

  def index
    @staff_datas = Staff.enable.company_filter.order("id ASC")
    if SmtpStatus.company_filter.exists?
      @default_sender = SmtpStatus.company_filter.first[:from_name]
    else
      @default_sender = ""
    end

    #error msg
    gon.error = Rails.application.config.error
  end

  def create
    p params
    date = params["reserve-date"]
    range = params["js-hour"]
    template_id = params["js-temp"]
    job_name = params["job_name"]
    staffs = params["reserve"]
    staff_ids = []
    from_name = params["js-template-sender"]
    subject = params["js-template-subject"]
    message = params["js-template-message"]
    file_name = params["js-template-filename"].to_s

    staffs.each do |key, value|
      if value == "1"
        staff_ids.push(key)
      end
    end

    ActiveRecord::Base.transaction do
      mrObj = MailReservation.new()
      mrObj.mail_template_id = template_id
      mrObj.job_name = job_name
      mrObj.reserved_date = Date.parse(date)
      send_time_zone_id = SendTimeZone.where(:display_name => range).first.id
      mrObj.send_time_zone_id = send_time_zone_id
      mrObj.reserved_at = Time.parse(date.to_s + " " + SendTimeZone.find(send_time_zone_id).start_time_at.strftime("%H:%M:%S"))
      mrObj.serial_number = ""
      mrObj.save!()
      mrObj.serial_number = Digest::MD5.hexdigest(mrObj.id.to_s)
      mrObj.save!()

      mail_temp = MailTemplate.where(id: template_id).first
      send_obj = SendMail.new()
      send_obj.mail_reservation_id = mrObj.id
      send_obj.from_name = from_name
      send_obj.subject = subject
      send_obj.message = message
      send_obj.link_flag = mail_temp.link_flag
      send_obj.file_name = file_name
      send_obj.attach_flag = mail_temp.attach_flag
      send_obj.attached_type_id = mail_temp.attached_type_id
      send_obj.save!()

      staff_ids.each do |id|
        smObj = SendMember.new()
        smObj.mail_reservation_id = mrObj.id
        smObj.staff_id = id
        smObj.save!()
      end
    end

    redirect_to mail_history_url, notice: "登録しました"
  end

  def get_mail_message
    data = MailTemplate.select("subject, message, attach_flag, file_name").where("id = ?", params[:id])
    render json: data
  end

  private

  def set_templates
    @template_datas = MailTemplate.enable.company_filter.order("updated_at DESC").pluck(:subject, :id)
    @js_css_root = controller_path
  end
end

testmail/app/controllers/mail_template/main_controller.rb
class MailTemplate::MainController < ApplicationController
  before_action :set_js_css_path, only: [:index]

  def index
    @template_datas = MailTemplate.enable.company_filter.order("updated_at DESC").page(params[:page])

    #error msg
    gon.error = Rails.application.config.error
  end

  def create
    tra_type = params["tra_type"]

    @template_datas = MailTemplate.new
    @template_datas.subject = params["title"]
    @template_datas.message = params["message"]

    @template_datas.link_flag = tra_type[:link]
    @template_datas.attach_flag = tra_type[:file]
    file_name = params["filename"]
    if tra_type[:file] == "1"
      @template_datas.attached_type_id = params["js-at-type"]

      if file_name.present?
        ext = ""
        if @template_datas.attached_type_id == AttachedTypes::DOCX
          ext = ".docx"
        elsif @template_datas.attached_type_id == AttachedTypes::XLSX
          ext = ".xlsx"
        else
          ext = ".zip"
        end
        if File.extname(file_name) != ext
          file_name = File.basename(file_name, '.*') + ext
        end
      end
    else
      @template_datas.attached_type_id = 1
    end

    @template_datas.file_name = file_name

    # render :index
    if @template_datas.save()
      redirect_to mail_template_index_url, notice: "登録しました"
    else
      logger.error @template_datas.errors.messages
      redirect_to :index
    end
  end

  def destroy
    MailTemplate.update(params[:id], {del_flag: 1})
    redirect_to mail_template_index_url, notice: "削除しました"
  end

  def get_data
    data = MailTemplate.select("subject, message, link_flag, file_name, attach_flag, attached_type_id").where("id = ?", params[:id])
    render json: data
  end

  def update

    tra_type = params["update_tra_type"]
    file_name = params["filename"]
    at_type = params["js-update-at-type"].to_i

    # 添付型以外は添付ファイルの種類は「添付なし」
    if tra_type[:file] != "1"
      at_type = AttachedTypes::NONE
    else
      if file_name.present?
        ext = ""
        if at_type == AttachedTypes::DOCX
          ext = ".docx"
        elsif at_type == AttachedTypes::XLSX
          ext = ".xlsx"
        else
          ext = ".zip"
        end
        if File.extname(file_name) != ext
          file_name = File.basename(file_name, '.*') + ext
        end
      end
    end

    result_flag = MailTemplate.update(params[:id], {subject: params["title"], message: params["message"],
      file_name: file_name, link_flag: tra_type[:link], attach_flag: tra_type[:file], attached_type_id: at_type})

    if result_flag
      redirect_to mail_template_index_url, notice: "更新しました"
    else
      logger.error ""
      redirect_to :index
    end
  end

  def get_filter_data
    word = params[:search_word]

    data = []
    MailTemplate.enable.company_filter.order("updated_at DESC").each do |mail_template|

      if mail_template.subject.to_s.include?(word)
        write_data mail_template, data
      end

    end
    render :json => {:status => 200, :data => data}, :status => 200
  end

  private
    def write_data mail_template, data
      no = data.size + 1
      data << {
          :id => no,
          :subject => mail_template.subject,
          :link_flag => mail_template.link_flag,
          :attach_flag => mail_template.attach_flag,
          :updated_at => mail_template.updated_at.strftime("%Y/%m/%d %H:%M:%S")
        }
    end

    def set_js_css_path
      @js_css_root = controller_path
      @attached_types = AttachedTypes.enable.where("id > 1").pluck(:name_ja, :id)
    end
end

testmail/app/controllers/top/main_controller.rb
require 'csv'
require 'nkf'

class Top::MainController < ApplicationController
  protect_from_forgery except: :create_download

  #elb health_check
  def health_check
    if valid.include?(params[:path])
      render :template => File.join('static', params[:path])
    end
  end

  def index
    #raise IpAddressRejected

    # Get informations.
    # @informations = Information.limit(10).order("created_at DESC")

    # Get logs.
    # @logs = Logs.limit(10).order("created_at DESC")

    # Get User name.
    @users = User.select(:email, :id).each_with_object({}) { |user, data| data[user.id] = user.email}

    #error msg
    gon.error = Rails.application.config.error

  end

  def download
    redirect_to action: 'index' if current_user.profile.auth_type.name != "admin"
  end

  def create_download
    redirect_to action: 'index' if current_user.profile.auth_type.name != "admin"

    start_period = Time.parse((params["start_date"].present? ? params["start_date"] : "2014-01-01") + " 00:00:00")
    end_period = Time.parse((params["end_date"].present? ? params["end_date"] : Time.now.to_date.to_s) + " 00:00:00") + 9.hours + 1.days

    hash = {}

    Logs.where(:user_id.ne => "", :user_id.exists => true, :created_at.gte => start_period, :created_at.lte => end_period).each do |log|
      next if log.request_path.index("/users/get") or log.request_path.index("assets") or log.request_path.index("stylesheet") or log.request_path.index("javascript")
      next if log.method != "GET"

      # Date to key
      date = log.created_at.to_date.to_s

      path = log.request_path.split("?")[0]

      hash[date] = {} if !hash.has_key? date
      hash[date][path] = {} if !hash[date].has_key? path
      hash[date][path][log.user_id] = 0 if !hash[date][path].has_key? log.user_id
      hash[date][path][log.user_id] += 1
    end

    master = {
      "/" => "トップページ",
      "/register_route" => "登録経路",
      "/usage_distribution" => "利用回数分布",
      "/retention_rate" => "定着率",
      "/customer_journey" => "カスタマージャーニー",
      "/users/sign_in" => "サインイン",
      "/users/sign_up" => "サインアップ",
      "/users/sign_out" => "サインアウト"
    }

    header = ["Date", "Title", "Path" ,"PV", "UU"]
    generated_csv = CSV.generate(row_sep: "\r\n", :encoding => "SJIS") do |csv|
      csv << header
      hash.each do |date, value|
        value.each do |path, data|
          pv = data.inject(0) { |num, (key,val)| num += val }
          uu = data.count
          title = master.key?(path) ? master[path] : "Other"
          title = "管理ツール" if path.index("admin")
          csv << [date, title.encode("Shift_JIS"), path, pv, uu]
        end
      end
    end

    file_name = "tmp/pv_uu_#{start_period}_#{end_period}_#{ENV['RAILS_ENV']}.csv"
    send_data generated_csv.encode('Shift_JIS', :invalid => :replace, :undef => :replace), type: 'text/csv; charset=shift_jis; header=present', disposition: "attachment; filename=#{file_name}"
  end
end

testmail/app/helpers/beacon/main_helper.rb
module Beacon::MainHelper
end

testmail/app/helpers/mail_history/main_helper.rb
module MailHistory::MainHelper
end

testmail/app/helpers/mail_reservation/main_helper.rb
module MailReservation::MainHelper
end

testmail/app/helpers/mail_template/main_helper.rb
module MailTemplate::MainHelper
end

testmail/app/helpers/open_report/main_helper.rb
module OpenReport::MainHelper
end

testmail/app/views/mail_template/main/index.html.slim
.main
  h4 メール作成

  .row
    .col-md-4
      #search-box
        = form_tag(mail_template_get_filter_data_url, :remote => true, :id => "template_filter_form", :class => "contents-search") do
          = text_field_tag :search_word, nil, :placeholder => "検索", :class => "form-control"
    .col-md-8.contents-button
      ul.text-right
        li
          button#js-disp-modal.btn.btn-success 新規作成

  .row
    .col-md-12.csv-sheet
      table.table.table-condensed.table-hover.table-striped
        thead
          tr
            th No
            th メール件名
            th.text-center URL型
            th.text-center 添付型
            th 更新日時
            th
        tbody#js-template-tbody
          - if @template_datas.blank?
            tr
              td.text-center colspan=7 データがありません
          - else
            - @template_datas.each_with_index do |data, count|
              tr
                td
                  - if @page.blank?
                    = count + 1
                  - else
                    = count + 1 + (@page.to_i - 1 ) * 10
                td
                  = data.subject
                td.text-center
                  = data.link_flag ? "<span class='glyphicon glyphicon-ok' aria-hidden='true' style='color: red'></span>".html_safe : "<span class='glyphicon glyphicon-minus' aria-hidden='true' style='color: blue'></span>".html_safe
                td.text-center
                  = data.attach_flag ? "<span class='glyphicon glyphicon-ok' aria-hidden='true' style='color: red'></span>".html_safe : "<span class='glyphicon glyphicon-minus' aria-hidden='true' style='color: blue'></span>".html_safe
                td
                  = data.updated_at.strftime("%Y/%m/%d %H:%M:%S")
                td.text-right
                  = link_to "送信予約", mail_reservation_url(id: data.id), class: "btn btn-success"
                  '
                  = link_to "編集", "#", class: "js-template-update btn btn-success", value: data.id
                  '
                  = link_to "削除", data, class: "btn btn-success", method: :delete, data: {confirm: "削除します。よろしいですか？"}

#js-template-modal.modal.fade aria-hidden="true" aria-labelledby="remoteModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title 新規作成
      .modal-body
        = form_tag("", id: "js-template-form", :multipart => true ) do
          .row
            label.col-md-3 メール件名
            .col-md-9
              input#js-template-title.form-control type="text" name="title"
          .row
            label.col-md-3 本文
            .col-md-9
              textarea#js-template-message.form-control rows="10" name="message"
          .row
            label.col-md-3 タイプ
            .col-md-9
              table
                tbody
                  tr
                    td
                      = check_box 'tra_type' ,'link'
                    td URL型
                  tr
                    td
                      = check_box 'tra_type' ,'file'
                    td 添付型
                    td
                      = select_tag "js-at-type", options_for_select(@attached_types), class: "form-control"

          .row
            label.col-md-3 添付ファイル名
            .col-md-9
              /= file_field :file, :csv, multiple: false, name: "attachment_file"
              input#js-template-filename.form-control type="text" name="filename"

        .modal-footer
          button#js-add-button.btn.btn-primary type="button" 登録
          button.btn.btn-default type="button" data-dismiss="modal" 閉じる

#js-template-update-modal.modal.fade aria-hidden="true" aria-labelledby="remoteModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title 編集
      .modal-body
        = form_tag("", id: "js-template-update-form", method: "PATCH") do
          .row
            label.col-md-3 メール件名
            .col-md-9
              input#js-template-update-title.form-control type="text" name="title"
          .row
            label.col-md-3 本文
            .col-md-9
              textarea#js-template-update-message.form-control rows="10" name="message"
          .row
            label.col-md-3 タイプ
            .col-md-9
              table
                tbody
                  tr
                    td
                      = check_box 'update_tra_type' ,'link'
                    td URL型
                  tr
                    td
                      = check_box 'update_tra_type' ,'file'
                    td 添付型
                    td
                      = select_tag "js-update-at-type", options_for_select(@attached_types), class: "form-control"

          .row
            label.col-md-3 添付ファイル名
            .col-md-9
              /= file_field :file, :csv, multiple: false, name: "attachment_file"
              input#js-template-update-filename.form-control type="text" name="filename"

      .modal-footer
        button#js-update-button.btn.btn-primary type="button" 更新
        button.btn.btn-default type="button" data-dismiss="modal" 閉じる